### ISSUE TITLE
[regression in 0.8] error: no such file or directory: '../libxputty/libxputty/libxputty.a'

### ISSUE THREAD

**Issue by yurivict** [brummer10/Fluida.lv2#15]
```
cc -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include  -D_FORTIFY_SOURCE=2 -I. -I./dsp -I./plugin -fPIC -DPIC -O2 -Wall -funroll-loops -fstack-protector -ffast-math -fomit-frame-pointer -fstrength-reduce `pkg-config --cflags --libs fluidsynth` -fdata-sections -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,--exclude-libs,ALL  -Wl,-z,nodelete fluida_ui.c -I../libxputty/libxputty/include/ -Wl,-z,noexecstack -Wl,--no-undefined -fvisibility=hidden -L. ../libxputty/libxputty/libxputty.a -shared `pkg-config --cflags --libs cairo x11` -lm -o Fluida_ui.so
cc: error: no such file or directory: '../libxputty/libxputty/libxputty.a'
cc: warning: optimization flag '-fstrength-reduce' is not supported [-Wignored-optimization-argument]
gmake[2]: *** [Makefile:107: Fluida] Error 1
```

libxputty.a isn't built.

FreeBSD 13.1 STABLE

**Comment by yurivict** [comment]
```
===>  Building for fluida-lv2-0.8
gmake[1]: Entering directory '/disk-samsung/freebsd-ports/audio/fluida-lv2/work/Fluida.lv2-0.8'
gmake[2]: Entering directory '/disk-samsung/freebsd-ports/audio/fluida-lv2/work/Fluida.lv2-0.8'
gmake[2]: warning: -j1 forced in submake: resetting jobserver mode.
c++ -std=c++11  -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include  -D_FORTIFY_SOURCE=2 -I. -I./dsp -I./plugin -fPIC -DPIC -O2 -Wall -funroll-loops -fstack-protector -ffast-math -fomit-frame-pointer -fstrength-reduce `pkg-config --cflags --libs fluidsynth` -fdata-sections -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,--exclude-libs,ALL  fluida.cpp XSynth.cpp  -fstack-protector-strong  -I.  -lm -pthread -lpthread -shared -lm -Wl,-z,noexecstack -Wl,--no-undefined -fvisibility=hidden `pkg-config --cflags --libs fluidsynth` -o Fluida.so
c++: warning: optimization flag '-fstrength-reduce' is not supported [-Wignored-optimization-argument]
c++: warning: optimization flag '-fstrength-reduce' is not supported [-Wignored-optimization-argument]
fluida.cpp:521:43: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_on)) {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:521:43: note: remove extraneous parentheses around the comparison to silence this warning
    if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_on)) {
        ~                                 ^                     ~
fluida.cpp:521:43: note: use '=' to turn this equality comparison into an assignment
    if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_on)) {
                                          ^~
                                          =
fluida.cpp:525:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_lev)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:525:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_lev)) {
               ~                                 ^                      ~
fluida.cpp:525:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_lev)) {
                                                 ^~
                                                 =
fluida.cpp:529:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_width)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:529:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_width)) {
               ~                                 ^                        ~
fluida.cpp:529:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_width)) {
                                                 ^~
                                                 =
fluida.cpp:533:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_damp)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:533:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_damp)) {
               ~                                 ^                       ~
fluida.cpp:533:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_damp)) {
                                                 ^~
                                                 =
fluida.cpp:537:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_size)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:537:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_size)) {
               ~                                 ^                       ~
fluida.cpp:537:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_size)) {
                                                 ^~
                                                 =
fluida.cpp:541:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_on)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:541:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_on)) {
               ~                                 ^                        ~
fluida.cpp:541:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_on)) {
                                                 ^~
                                                 =
fluida.cpp:545:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_type)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:545:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_type)) {
               ~                                 ^                          ~
fluida.cpp:545:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_type)) {
                                                 ^~
                                                 =
fluida.cpp:549:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_depth)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:549:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_depth)) {
               ~                                 ^                           ~
fluida.cpp:549:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_depth)) {
                                                 ^~
                                                 =
fluida.cpp:553:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_speed)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:553:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_speed)) {
               ~                                 ^                           ~
fluida.cpp:553:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_speed)) {
                                                 ^~
                                                 =
fluida.cpp:557:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_lev)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:557:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_lev)) {
               ~                                 ^                         ~
fluida.cpp:557:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_lev)) {
                                                 ^~
                                                 =
fluida.cpp:561:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_voices)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:561:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_voices)) {
               ~                                 ^                            ~
fluida.cpp:561:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_voices)) {
                                                 ^~
                                                 =
fluida.cpp:565:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_channel_pressure)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:565:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_channel_pressure)) {
               ~                                 ^                               ~
fluida.cpp:565:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_channel_pressure)) {
                                                 ^~
                                                 =
fluida.cpp:626:34: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
                    flags = ~(-1 << 15);
                              ~~ ^
fluida.cpp:1060:1: warning: duplicate 'extern' declaration specifier [-Wduplicate-decl-specifier]
LV2_SYMBOL_EXPORT
^
/usr/local/include/lv2/core/lv2.h:373:5: note: expanded from macro 'LV2_SYMBOL_EXPORT'
    LV2_SYMBOL_EXTERN __attribute__((visibility("default")))
    ^
/usr/local/include/lv2/core/lv2.h:360:29: note: expanded from macro 'LV2_SYMBOL_EXTERN'
#  define LV2_SYMBOL_EXTERN extern "C"
                            ^
fluida.cpp:159:30: warning: private field 'control' is not used [-Wunused-private-field]
    const LV2_Atom_Sequence* control;
                             ^
fluida.cpp:166:24: warning: private field 'notify_port' is not used [-Wunused-private-field]
    LV2_Atom_Sequence* notify_port;
                       ^
16 warnings generated.
cc -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include  -D_FORTIFY_SOURCE=2 -I. -I./dsp -I./plugin -fPIC -DPIC -O2 -Wall -funroll-loops -fstack-protector -ffast-math -fomit-frame-pointer -fstrength-reduce `pkg-config --cflags --libs fluidsynth` -fdata-sections -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,--exclude-libs,ALL  -Wl,-z,nodelete fluida_ui.c -I../libxputty/libxputty/include/ -Wl,-z,noexecstack -Wl,--no-undefined -fvisibility=hidden -L. ../libxputty/libxputty/libxputty.a -shared `pkg-config --cflags --libs cairo x11` -lm -o Fluida_ui.so
cc: error: no such file or directory: '../libxputty/libxputty/libxputty.a'
cc: warning: optimization flag '-fstrength-reduce' is not supported [-Wignored-optimization-argument]
gmake[2]: *** [Makefile:107: Fluida] Error 1
gmake[2]: Leaving directory '/disk-samsung/freebsd-ports/audio/fluida-lv2/work/Fluida.lv2-0.8/Fluida'
gmake[1]: *** [Makefile:32: Fluida] Error 2
gmake[1]: Leaving directory '/disk-samsung/freebsd-ports/audio/fluida-lv2/work/Fluida.lv2-0.8'
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1
```

**Comment by brummer10** [comment]
This looks as if you try to build from the Source Code.zip file provided by github. That will not work as stated in the announce message (missing submodules). Please use [Fluida_0.8.tar.gz](https://github.com/brummer10/Fluida.lv2/releases/download/v0.8/Fluida_0.8.tar.gz)
The warnings may remain, I'll look tomorrow into them, but at least it will build libxputty then.

**Comment by yurivict** [comment]
Tarball has the same problem.

**Comment by brummer10** [comment]
As I wrote, please provide the full build log, in the one above I could see that make didn't enter libxputty at all, if the same happen with the tarball, that would be very, very strange.

**Comment by yurivict** [comment]
```
===>  Building for fluida-lv2-0.8
gmake[1]: Entering directory '/disk-samsung/freebsd-ports/audio/fluida-lv2/work/Fluida_0.8'
gmake[2]: Entering directory '/disk-samsung/freebsd-ports/audio/fluida-lv2/work/Fluida_0.8'
gmake[2]: warning: -j1 forced in submake: resetting jobserver mode.
c++ -std=c++11  -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include  -D_FORTIFY_SOURCE=2 -I. -I./dsp -I./plugin -fPIC -DPIC -O2 -Wall -funroll-loops -fstack-protector -ffast-math -fomit-frame-pointer -fstrength-reduce `pkg-config --cflags --libs fluidsynth` -fdata-sections -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,--exclude-libs,ALL  fluida.cpp XSynth.cpp  -fstack-protector-strong  -I.  -lm -pthread -lpthread -shared -lm -Wl,-z,noexecstack -Wl,--no-undefined -fvisibility=hidden `pkg-config --cflags --libs fluidsynth` -o Fluida.so
c++: warning: optimization flag '-fstrength-reduce' is not supported [-Wignored-optimization-argument]
c++: warning: optimization flag '-fstrength-reduce' is not supported [-Wignored-optimization-argument]
fluida.cpp:521:43: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_on)) {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:521:43: note: remove extraneous parentheses around the comparison to silence this warning
    if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_on)) {
        ~                                 ^                     ~
fluida.cpp:521:43: note: use '=' to turn this equality comparison into an assignment
    if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_on)) {
                                          ^~
                                          =
fluida.cpp:525:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_lev)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:525:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_lev)) {
               ~                                 ^                      ~
fluida.cpp:525:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_lev)) {
                                                 ^~
                                                 =
fluida.cpp:529:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_width)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:529:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_width)) {
               ~                                 ^                        ~
fluida.cpp:529:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_width)) {
                                                 ^~
                                                 =
fluida.cpp:533:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_damp)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:533:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_damp)) {
               ~                                 ^                       ~
fluida.cpp:533:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_damp)) {
                                                 ^~
                                                 =
fluida.cpp:537:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_size)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:537:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_size)) {
               ~                                 ^                       ~
fluida.cpp:537:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_rev_size)) {
                                                 ^~
                                                 =
fluida.cpp:541:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_on)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:541:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_on)) {
               ~                                 ^                        ~
fluida.cpp:541:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_on)) {
                                                 ^~
                                                 =
fluida.cpp:545:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_type)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:545:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_type)) {
               ~                                 ^                          ~
fluida.cpp:545:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_type)) {
                                                 ^~
                                                 =
fluida.cpp:549:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_depth)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:549:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_depth)) {
               ~                                 ^                           ~
fluida.cpp:549:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_depth)) {
                                                 ^~
                                                 =
fluida.cpp:553:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_speed)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:553:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_speed)) {
               ~                                 ^                           ~
fluida.cpp:553:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_speed)) {
                                                 ^~
                                                 =
fluida.cpp:557:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_lev)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:557:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_lev)) {
               ~                                 ^                         ~
fluida.cpp:557:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_lev)) {
                                                 ^~
                                                 =
fluida.cpp:561:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_voices)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:561:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_voices)) {
               ~                                 ^                            ~
fluida.cpp:561:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_chorus_voices)) {
                                                 ^~
                                                 =
fluida.cpp:565:50: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_channel_pressure)) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fluida.cpp:565:50: note: remove extraneous parentheses around the comparison to silence this warning
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_channel_pressure)) {
               ~                                 ^                               ~
fluida.cpp:565:50: note: use '=' to turn this equality comparison into an assignment
    } else if ((((LV2_Atom_URID*)property)->body == uris->fluida_channel_pressure)) {
                                                 ^~
                                                 =
fluida.cpp:626:34: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
                    flags = ~(-1 << 15);
                              ~~ ^
fluida.cpp:1060:1: warning: duplicate 'extern' declaration specifier [-Wduplicate-decl-specifier]
LV2_SYMBOL_EXPORT
^
/usr/local/include/lv2/core/lv2.h:373:5: note: expanded from macro 'LV2_SYMBOL_EXPORT'
    LV2_SYMBOL_EXTERN __attribute__((visibility("default")))
    ^
/usr/local/include/lv2/core/lv2.h:360:29: note: expanded from macro 'LV2_SYMBOL_EXTERN'
#  define LV2_SYMBOL_EXTERN extern "C"
                            ^
fluida.cpp:159:30: warning: private field 'control' is not used [-Wunused-private-field]
    const LV2_Atom_Sequence* control;
                             ^
fluida.cpp:166:24: warning: private field 'notify_port' is not used [-Wunused-private-field]
    LV2_Atom_Sequence* notify_port;
                       ^
16 warnings generated.
cc -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include  -D_FORTIFY_SOURCE=2 -I. -I./dsp -I./plugin -fPIC -DPIC -O2 -Wall -funroll-loops -fstack-protector -ffast-math -fomit-frame-pointer -fstrength-reduce `pkg-config --cflags --libs fluidsynth` -fdata-sections -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,--exclude-libs,ALL  -Wl,-z,nodelete fluida_ui.c -I../libxputty/libxputty/include/ -Wl,-z,noexecstack -Wl,--no-undefined -fvisibility=hidden -L. ../libxputty/libxputty/libxputty.a -shared `pkg-config --cflags --libs cairo x11` -lm -o Fluida_ui.so
cc: error: no such file or directory: '../libxputty/libxputty/libxputty.a'
cc: warning: optimization flag '-fstrength-reduce' is not supported [-Wignored-optimization-argument]
gmake[2]: *** [Makefile:107: Fluida] Error 1
gmake[2]: Leaving directory '/disk-samsung/freebsd-ports/audio/fluida-lv2/work/Fluida_0.8/Fluida'
gmake[1]: *** [Makefile:32: Fluida] Error 2
gmake[1]: Leaving directory '/disk-samsung/freebsd-ports/audio/fluida-lv2/work/Fluida_0.8'
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1
```

**Comment by brummer10** [comment]
What ist gmake?

**Comment by yurivict** [comment]
GNU Make.

**Comment by brummer10** [comment]
So I've really no idea what goes wrong here. This is what I get when I run gmake from top level on the tarball:
```
Fluida_0.8$ gmake
Submodule up to date
gmake[1]: Verzeichnis „/home/brummer/Downloads/Fluida_0.8/libxputty“ wird betreten
gmake[2]: Verzeichnis „/home/brummer/Downloads/Fluida_0.8/libxputty/Build“ wird betreten
HAVE_XXD="1"
HAVE_XXDI_PL=""
HAVE_KNOWN_LDEMULATION=""
LDEMULATION=""
HAVE_LD_GOLD="1"
Using xxd -i
```
libxputty is set as dependency for Fluida in the makefile and should be build before Fluida. That is the same as in all apps I've written using libxputty. Therefore it is needed to restrict the jobserver to 1 job, that is done in the toplevel makefile. 
What happen when you go to the libxputty directory and start make from there? Did libxputty build?

**Comment by yurivict** [comment]
libxputty builds separately, in its directory.

Makefile says that Fluida depends on libxputty.
Then libxputty has this conditional:
```
ifeq (,$(filter $(NOGOAL),$(MAKECMDGOALS)))
        @exec $(MAKE) -j 1 -C $@ $(MAKECMDGOALS)
endif
```
It probably excludes any build there. It's hard to tell what is it supposed to do.

**Comment by brummer10** [comment]
This is needed for building the app for the MOD environment.
NOGOAL is defined above as:
`NOGOAL := mod install all`

when one of the above targets been given on the command-line, libxputty will be excluded. 
We don't wont it to be installed -> install
We build it for the MOD -> mod
We build it as part of a app bundle were libxputty is already build -> all

maybe you run gmake all ?

**Comment by yurivict** [comment]
Yes, all GNU make projects build with ```gmake all```.

**Comment by yurivict** [comment]
Ok, it builds with the empty target.
